### ISSUE TITLE
appkey是私钥，不能作为参数传输

### ISSUE THREAD

**Issue by RobinzZH** [tswjs/open-platform#10]
https://github.com/tswjs/open-platform/blob/e1e462121ad1b52158b9b346ee54b708eb225d43/packages/open-platform-api/lib/openapi.js#L259

**Comment by Zack921** [comment]
![image](https://user-images.githubusercontent.com/32858043/150067988-ac814df3-3220-4fe5-b95a-914454497f14.png)
