### ISSUE TITLE
tsw2上报的日志信息不全

### ISSUE THREAD

**Issue by vivialex** [tswjs/open-platform#12]
<img width="862" alt="wecom-temp-8488e79abcb6942d9672457355dfd902" src="https://user-images.githubusercontent.com/13270284/150794454-b70018c7-6d6f-4733-847b-633555e3ceac.png">
<img width="1529" alt="wecom-temp-2e10bef41503c5e946342faa98ce5b87" src="https://user-images.githubusercontent.com/13270284/150794478-0a8c499a-9867-4dea-b12f-92f9b96146a9.png">
debug一下发现，open-platform-plugin是从context获取host、clientip等，但context里并没有这些值

**Comment by realyuyanan** [comment]
> 

开放平台日志信息预览，取是上报日志的第一行，也就是下面那条日志，确实是没有带上host、端口号等一些信息。今天修一下。
![image](https://user-images.githubusercontent.com/22365107/150914165-7204e930-548f-4cdd-8f83-e0e246ecf346.png)

**Comment by Zack921** [comment]
![image](https://user-images.githubusercontent.com/32858043/150918299-90ccf30f-1c7d-48ee-80a2-d97a903711b7.png)
