### ISSUE TITLE
希望fetch的timeout时间可以自行配置

### ISSUE THREAD

**Issue by loviselu** [tswjs/open-platform#21]
https://github.com/tswjs/open-platform/blob/357868c8e02e391f29e04db6e09c7e8b0453099a/packages/open-platform-api/lib/openapi.js#L49

这个地方写了默认3s超时，但没有给到用户方可配置。目前遇到包比较大，上传日志会超时的，希望能改大这个值同时也可以配置这个值

**Comment by Zack921** [comment]
get. 我处理下

**Comment by Zack921** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/32858043/165320047-9cba961d-5c1c-4e82-8732-74b9322f88c5.png">
